const dummyChats = [
  {
    id: 1,
    name: "Ali Ahmed",
    message: "Hey Bilal! Are we meeting today?",
    time: "10:30 AM",
    online: true,
    unread: 2,
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 2,
    name: "Sara Khan",
    message: "See you tomorrow 😊",
    time: "09:45 AM",
    online: false,
    unread: 0,
    avatar: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: 3,
    name: "John Smith",
    message: "Meeting starts in 10 minutes.",
    time: "Yesterday",
    online: true,
    unread: 5,
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: 4,
    name: "Ayesha",
    message: "Thank you ❤️",
    time: "Monday",
    online: false,
    unread: 0,
    avatar: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: 5,
    name: "Ahmed Raza",
    message: "Can you send the files?",
    time: "Sunday",
    online: true,
    unread: 1,
    avatar: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: 6,
    name: "Fatima Noor",
    message: "Good Night 🌙",
    time: "Saturday",
    online: false,
    unread: 0,
    avatar: "https://i.pravatar.cc/150?img=47",
  },
];

export default dummyChats;